import { readFileSync } from "node:fs";
import assert from "node:assert/strict";

const html = readFileSync(new URL("../index.html", import.meta.url), "utf8");
const script = readFileSync(new URL("../script.js", import.meta.url), "utf8");
const style = readFileSync(new URL("../style.css", import.meta.url), "utf8");

assert.match(html, /id="participant-select"/, "UI should let researchers switch participants.");
assert.match(html, /id="add-participant"/, "UI should let researchers add another participant.");
assert.match(html, /id="delete-participant"/, "UI should let researchers delete the active participant.");
assert.match(script, /code: `P-\$\{String\(index\)\.padStart\(3, "0"\)\}`/, "Participant labels should start from P-001.");
assert.match(script, /participants:/, "State should store multiple participants.");
assert.match(script, /activeParticipantId/, "State should track the active participant.");
assert.match(script, /getActiveParticipant/, "Code should read data through the active participant.");
assert.match(script, /participantId === participant\.id/, "Generated records should be scoped to the active participant.");
assert.match(html, /生命中的關鍵事件/, "UI should include the new life event type selection screen.");
assert.match(html + script, /生理需求/, "UI should offer the physiology event type.");
assert.match(html + script, /安全需求/, "UI should offer the safety event type.");
assert.match(html + script, /愛與歸屬/, "UI should offer the belonging event type.");
assert.match(html + script, /尊重需求/, "UI should offer the esteem event type.");
assert.match(html + script, /自我實現/, "UI should offer the self-actualization event type.");
assert.match(script, /selectedEventType/, "State should track the selected life event type.");
assert.match(script, /width:\s*1512/, "UI should use the Figma frame width as the layout baseline.");
assert.match(script, /height:\s*982/, "Non-generation pages should use the Figma frame height as the layout baseline.");
assert.match(script, /generateHeight:\s*1568/, "The generation page should keep the taller Figma frame height.");
assert.match(script, /updateViewportScale/, "UI should scale the Figma-sized frame to fit the current browser viewport.");
assert.match(script, /window\.addEventListener\("resize",\s*updateViewportScale\)/, "UI should recalculate frame scaling when the viewport changes.");

assert.doesNotMatch(html + script, /此時此刻/, "The UI/mock output should not use the stiff phrase 此時此刻.");
assert.doesNotMatch(html + script, /我站在/, "Mock monologues should not force a spatial time-travel opening.");
assert.doesNotMatch(html + script, /聽完|聽到這段|第一個反應/, "Mock output should not sound like a listener commenting on the participant's story.");
assert.doesNotMatch(html + script, /這件事對我來說|旁人的故事/, "Mock output should not use abstract template phrasing.");
assert.match(script, /pickVariant/, "Mock output should vary wording instead of using one fixed public template.");
assert.match(script, /我看到|我記得|我注意到/, "Mock output should start from natural observation language.");
assert.match(html + script, /當下/, "The present-time condition should be labeled 當下.");
assert.match(script, /present:\s*"現在"/, "The record matrix should match the Figma label 現在.");
assert.match(html + script, /真實/, "The experimental condition should be labeled 真實.");
assert.match(html + script, /反事實/, "The experimental condition should be labeled 反事實.");
assert.doesNotMatch(html + script, /請先完成目前條件/, "The UI should not show extra instructional hint text.");

assert.match(html + script, /自動寫入 Notion/, "The UI should clarify that API mode writes to Notion automatically.");
assert.doesNotMatch(html + script, /核可|退回|重生|審閱/, "The experiment UI should not imply subjective review/regeneration.");
assert.match(html, /<span class="stamp">V3<\/span>/, "The UI version stamp should match the current prompt version.");
assert.match(style, /body\s*\{[^}]*overflow:\s*hidden/s, "Non-generation pages should not scroll vertically.");
assert.match(style, /body\[data-step="generate"\]\s*\{[^}]*overflow-y:\s*auto/s, "Only the generation page should allow vertical scrolling.");
assert.match(style, /transform:\s*translate\(-50%, -50%\) scale\(var\(--design-scale\)\)/, "Non-generation frames should be centered and scaled to fit.");
assert.match(style, /height:\s*1568px/, "The generation frame should retain the Figma export height.");
assert.match(html, /noindex,\s*nofollow/, "The public preview should not invite search indexing.");
assert.match(style, /--shadow:\s*none/, "Panel shadows should stay disabled while the Figma layout is being aligned.");
assert.match(script, /if \(state\.activeStep !== "generate"\) return;/, "Heavy generation views should only render on the generation page.");
assert.match(script, /class="matrix-arrow"/, "The record matrix should render the arrow as an explicit grid column.");
assert.match(style, /grid-template-columns:\s*167px 20px repeat\(6, 167px\)/, "The record matrix columns should stay aligned to the Figma-sized cards.");
assert.match(script, /function queueSaveState/, "Typing should debounce localStorage writes to reduce UI stalls.");
assert.match(style, /\.event-type-card\.active\s*\{[^}]*background:\s*#050505/s, "The selected event type should be visually clear.");
assert.match(style, /prefers-reduced-motion:\s*reduce/, "Motion should respect reduced-motion preferences.");
